In [1]:
#1. Python program to add two Matrices

In [2]:
import numpy as np
M1 = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])

M2 = np.array([[5,8,1],
    [6,7,3],
    [4,5,9]])

X = (np.add(M1,M2))

print(X)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [3]:
#2. Python program to multiply two matrices

In [4]:
M1 = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])

M2 = np.array([[5,8,1],
    [6,7,3],
    [4,5,9]])

X = (np.dot(M1,M2))

print(X)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


In [5]:
#3. Python program for Matrix Product

In [6]:
import numpy as np
M1 = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])

M2 = np.array([[5,8,1],
    [6,7,3],
    [4,5,9]])
print(np.matmul(M1,M2))



[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


In [7]:
#4. Adding and Subtracting Matrices in Python

In [8]:
M1 = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])

M2 = np.array([[5,8,1],
    [6,7,3],
    [4,5,9]])

X = str(np.add(M1,M2))
y = str(np.subtract(M1,M2))

print('addition:'+ X,
     'subtraction:'+ y)

addition:[[17 15  4]
 [10 12  9]
 [11 13 18]] subtraction:[[ 7 -1  2]
 [-2 -2  3]
 [ 3  3  0]]


In [9]:
#5. Transpose a matrix in Single line in Python

In [10]:
M1 = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])

print(M1.transpose())



[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


In [11]:
#6. Python | Matrix creation of n*n

In [12]:
def matrix_creation(n):
    m = np.array(range(1,n*n+1))
    return m.reshape(n,n)
print(matrix_creation(4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
#7. Python | Get Kth Column of Matrix

In [14]:
def get_column (M1,K):
    return M1[:,K]
M1 = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])
print(get_column(M1,2))

[3 6 9]


In [15]:
#8. Python – Vertical Concatenation in Matrix

In [16]:

M1 = ([['a','b','c'],
    ['d','e','f'],
    ['g','h','i']])

M2 = ([['j','k','l'],
    ['m','n','o'],
    ['p','q','r']])

result = ([[0,0,0],
      [0,0,0],
      [0,0,0]])

for i in range(len(M1)):
    for j in range(len(M1[0])):
        result[i][j] = M1[i][j]+ M2[i][j]

print(result)

[['aj', 'bk', 'cl'], ['dm', 'en', 'fo'], ['gp', 'hq', 'ir']]


In [17]:
#9. Python program to check if a string is palindrome or not

In [3]:
def check_palindrome(x):
    if x == x[::-1]:
        return 'is palindrome'
    else :
        return 'not palindrome'
print(check_palindrome('eye'))
print(check_palindrome('letter'))

is palindrome
not palindrome


In [19]:
#10. Python program to check whether the string is Symmetrical or Palindrome

In [19]:
def check_symmetrical(n):
    b = len(n)
    k = n
    if b % 2 :
        mi = b//2 + 1
    else:
        mi = b//2 
    s1 = 0
    s2 = mi
    y = 0   

    while (s1 < mi and s2 < b):
        
        if (n[s1]== n[s2]):
            s1 = s1 + 1
            s2 = s2 + 1
        else:
            y = 1
            break
    
    if y == 0:
        return 'is symmetrical'
    else:
        return 'not symmetrical'

In [20]:
print(check_palindrome('radar'))
print(check_symmetrical('radar'))

is palindrome
not symmetrical


In [21]:
print(check_palindrome('abab'))
print(check_symmetrical('abab'))

not palindrome
is symmetrical


In [22]:
print(check_palindrome('madma'))
print(check_symmetrical('madma'))

not palindrome
is symmetrical


In [23]:
print(check_palindrome('love'))
print(check_symmetrical('love'))

not palindrome
not symmetrical
